<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Sun, 27 Aug 2017 09:41:16 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: iluyang.tk [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'iluyang.tk';
$cfg['Servers'][$i]['host'] = $MYSQL_HOST;
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = $MYSQL_ROOT_PASSWORD;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'xvQA]Hb.Y>KZ50oiUx.w4%[r2FEi!"h\\';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>