<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Sun, 12 Nov 2017 05:28:52 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: mysql56 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'mysql56';
$cfg['Servers'][$i]['host'] = '172.30.232.123';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'userATS';
$cfg['Servers'][$i]['password'] = 'f476RaxiexAI5vAd';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'C8`B[==-9h73aNj#\'iMwQjDFhJC0(Nsl';
$cfg['DefaultLang'] = 'zh_CN';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>