<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.7.4 setup script
 * Date: Sun, 27 Aug 2017 07:01:22 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: MySQL [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'MySQL';
$cfg['Servers'][$i]['host'] = '172.30.194.81';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = 'six6_gud8,lyp100tui.tk';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'CB`s0/R.B:GDn0WI8^H?/FnW,\'/ju0(V';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>